// Generated by gencpp from file IRIS/BSTX.msg
// DO NOT EDIT!


#ifndef IRIS_MESSAGE_BSTX_H
#define IRIS_MESSAGE_BSTX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace IRIS
{
template <class ContainerAllocator>
struct BSTX_
{
  typedef BSTX_<ContainerAllocator> Type;

  BSTX_()
    : pos_x(0)
    , pos_y(0)
    , pos_theta(0)
    , v_x(0)
    , v_y(0)
    , v_theta(0)
    , bola_x(0)
    , bola_y(0)  {
    }
  BSTX_(const ContainerAllocator& _alloc)
    : pos_x(0)
    , pos_y(0)
    , pos_theta(0)
    , v_x(0)
    , v_y(0)
    , v_theta(0)
    , bola_x(0)
    , bola_y(0)  {
  (void)_alloc;
    }



   typedef int64_t _pos_x_type;
  _pos_x_type pos_x;

   typedef int64_t _pos_y_type;
  _pos_y_type pos_y;

   typedef int64_t _pos_theta_type;
  _pos_theta_type pos_theta;

   typedef int64_t _v_x_type;
  _v_x_type v_x;

   typedef int64_t _v_y_type;
  _v_y_type v_y;

   typedef int64_t _v_theta_type;
  _v_theta_type v_theta;

   typedef int64_t _bola_x_type;
  _bola_x_type bola_x;

   typedef int64_t _bola_y_type;
  _bola_y_type bola_y;





  typedef boost::shared_ptr< ::IRIS::BSTX_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::IRIS::BSTX_<ContainerAllocator> const> ConstPtr;

}; // struct BSTX_

typedef ::IRIS::BSTX_<std::allocator<void> > BSTX;

typedef boost::shared_ptr< ::IRIS::BSTX > BSTXPtr;
typedef boost::shared_ptr< ::IRIS::BSTX const> BSTXConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::IRIS::BSTX_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::IRIS::BSTX_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::IRIS::BSTX_<ContainerAllocator1> & lhs, const ::IRIS::BSTX_<ContainerAllocator2> & rhs)
{
  return lhs.pos_x == rhs.pos_x &&
    lhs.pos_y == rhs.pos_y &&
    lhs.pos_theta == rhs.pos_theta &&
    lhs.v_x == rhs.v_x &&
    lhs.v_y == rhs.v_y &&
    lhs.v_theta == rhs.v_theta &&
    lhs.bola_x == rhs.bola_x &&
    lhs.bola_y == rhs.bola_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::IRIS::BSTX_<ContainerAllocator1> & lhs, const ::IRIS::BSTX_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace IRIS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::IRIS::BSTX_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::IRIS::BSTX_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::IRIS::BSTX_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::IRIS::BSTX_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::IRIS::BSTX_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::IRIS::BSTX_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::IRIS::BSTX_<ContainerAllocator> >
{
  static const char* value()
  {
    return "297a735316498be176d85aaa0928e9ed";
  }

  static const char* value(const ::IRIS::BSTX_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x297a735316498be1ULL;
  static const uint64_t static_value2 = 0x76d85aaa0928e9edULL;
};

template<class ContainerAllocator>
struct DataType< ::IRIS::BSTX_<ContainerAllocator> >
{
  static const char* value()
  {
    return "IRIS/BSTX";
  }

  static const char* value(const ::IRIS::BSTX_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::IRIS::BSTX_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 pos_x\n"
"int64 pos_y\n"
"int64 pos_theta\n"
"int64 v_x\n"
"int64 v_y\n"
"int64 v_theta\n"
"int64 bola_x\n"
"int64 bola_y\n"
;
  }

  static const char* value(const ::IRIS::BSTX_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::IRIS::BSTX_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos_x);
      stream.next(m.pos_y);
      stream.next(m.pos_theta);
      stream.next(m.v_x);
      stream.next(m.v_y);
      stream.next(m.v_theta);
      stream.next(m.bola_x);
      stream.next(m.bola_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BSTX_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::IRIS::BSTX_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::IRIS::BSTX_<ContainerAllocator>& v)
  {
    s << indent << "pos_x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.pos_x);
    s << indent << "pos_y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.pos_y);
    s << indent << "pos_theta: ";
    Printer<int64_t>::stream(s, indent + "  ", v.pos_theta);
    s << indent << "v_x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.v_x);
    s << indent << "v_y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.v_y);
    s << indent << "v_theta: ";
    Printer<int64_t>::stream(s, indent + "  ", v.v_theta);
    s << indent << "bola_x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.bola_x);
    s << indent << "bola_y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.bola_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRIS_MESSAGE_BSTX_H
